---
- name: download prometheus
  get_url:
    url: "{{ url_download }}"
    dest: /tmp/{{ tarball }}
    checksum: sha256:{{ prometheus_sha256 }}

- name: create dir {{ prom_dir }}
  file:
    path: "{{ prom_dir }}"
    state: directory
    mode: 0755

- name: create dir {{ prom_data }}
  file:
    path: "{{ prom_data }}"
    state: directory
    mode: 0755

- name: create config dir {{ prom_config }}
  file:
    path: "{{ prom_config }}"
    state: directory
    mode: 0755

- unarchive:
    src: /tmp/{{ tarball }}
    dest: /tmp/
    remote_src: yes

- name: remove old installation from {{ prom_dir }}
  file: path={{ prom_dir }}/prometheus state=absent

- name: install prometheus in {{ prom_dir }}
  command: mv /tmp/{{ untar_dir }} {{ prom_dir }}/prometheus

